// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  dashboardSidebar: [
    {type: 'autogenerated', dirName: 'responsible-ai-dashboard-mslearn'},
  ],

  contentSafetySidebar: [
    {type: 'autogenerated', dirName: 'azure-content-safety'},
  ],

  promptFlowSidebar: [
    {type: 'autogenerated', dirName: 'azure-prompt-flow'},
  ],

};

module.exports = sidebars;
